apiVersion: v1
kind: Service
metadata:
  name: k8ssandra-lb-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 9042
  selector:
    cassandra.datastax.com/cluster: k8ssandra
    cassandra.datastax.com/datacenter: dc1
  type: LoadBalancer
  loadBalancerIP: 
