apiVersion: v1
kind: Service
metadata:
  name: k8ssandra-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: cassandra-demo
  ports:
  - name: cql
    protocol: TCP
    port: 9042
    targetPort: 9042
    nodePort: 30942
