image:
  repository: janusgraph/janusgraph
  tag: 1.0.0
  pullPolicy: IfNotPresent

replicaCount: 1

## set your additional container-specific resource requests here
customContainerResources: {}

## set your additional container-specific environment vars here
customContainerEnv: {}

service:
  type: NodePort 
  portName: gremlin
  servicePort: 8182
  targetPort: 8182
  # nodePort: use to fix the port chosen by the cluster controller
  serviceAnnotations:

# provides the admin credentials for cassandra
# should be overwritten by app-specific setup
secretKeyRefs:
  superuser: 
    name: demo-superuser
    namespace: k8ssandra-operator

debugLevel: INFO

# storage backend properties (really should be overwritten)
storage:
  backend: cql
  cql_keyspace: appspecific_janusgraph_keyspace
  hostname: cluster-datacenter-service-hostname
  datacenter: cassandra-set-datacenter

# each property is converted from YAML to Java-style properties for JanusGraph
# intentionally left blank by default
properties:

# general indexing properties
indexingProperties:
  index.search.backend: lucene
  index.search.directory: /db/searchindex

# quirky elasticsearch details
elasticsearch:
  deploy: false
  rbac:
    create: true

# Gremlin Serializers that come _before_ the default latest one
serializerAdditions:

## if using local storage and indexing, choose whether or not to persist janus status
persistence:
  enabled: true  
  path: /db
  accessMode: ReadWriteOnce
  size: 4Gi  
  existingClaim:

## To use your own janusgraph.properties and gremlin-server.yaml, provide a
## custom ConfigMap in your k8s cluster (use the helm-created ConfigMap as a pattern).
configMapOverrideName: ""
